#!/bin/bash

echo "=== GitHub Repository Setup ==="
echo ""
echo "1. CREATE GITHUB REPOSITORY:"
echo "   Go to: https://github.com/new"
echo "   Repository name: my-kanopy-app"
echo "   Set to PUBLIC (required for Drone)"
echo "   DO NOT initialize with README"
echo ""
echo "2. AFTER CREATING REPO, RUN THESE COMMANDS:"
echo "   (Replace YOUR_USERNAME with your GitHub username)"
echo ""
echo "   git remote add origin https://github.com/YOUR_USERNAME/my-kanopy-app.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "3. CONFIGURE DRONE:"
echo "   Go to: https://drone.corp.mongodb.com"
echo "   Sign in with GitHub"
echo "   Activate your repository"
echo ""
echo "4. GET SECRETS (run on MongoDB infrastructure machine):"
echo "   See DEPLOYMENT_STEPS.md for detailed commands"
echo ""
echo "Your current directory is ready to push!"
echo "Directory: $(pwd)"
echo "Git status:"
git status --porcelain